------------------------------------------------------------------------
-- CSTZ.Topos.Sheaf
--
-- Paper §9, Thm 9.18: Sheaf topos.  [AP]
--
-- The site 𝔖 of κ-states with the Grothendieck topology generated
-- by the six triadic adjunctions as covering families.
------------------------------------------------------------------------

module CSTZ.Topos.Sheaf where

open import CSTZ.GF2
open import CSTZ.Vec
open import CSTZ.Category.Adjunction using (Axis ; κ-axis ; σ-axis ; τ-axis)

open import Data.Nat using (ℕ)
open import Data.List using (List)

------------------------------------------------------------------------
-- Paper §9, Def 9.17: The site of regimes

-- Objects: κ-states (subspaces of V*)
-- Morphisms: sub-regime inclusions
-- Topology: generated by the six triadic adjunctions

record Site (n : ℕ) : Set where
  field
    regime : List (GF2Vec n)  -- the κ-state (list of basis vectors)

-- A covering family is a collection of sub-regime inclusions
-- that jointly cover the whole regime.  The six triadic adjunctions
-- (three axes × two chiralities) generate the topology.

-- Paper §9, Thm 9.18:
-- The sheaf condition is order-independence of filtration (Prop 3.8):
-- local sections that agree on overlaps glue to a global section.
--
-- Single-axis families (3, each 1-dimensional) do NOT cover.
-- Two-axis families (12, each spanning GF(2)²) DO cover.
-- The topology is not trivial (proper subfamilies cover),
-- not discrete (single-axis sieves fail).
-- It is the UNIQUE S₃-invariant topology.

-- The number of covering sieves:
-- 1-axis: 3 sieves, none covering
-- 2-axis: 12 sieves, all covering
-- Full: 1 sieve (the maximal sieve), covering

-- Full verification: Verification.MonoidalCoherence (App B.28).
